#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
#reads and parses the shared memory written my mds02.c. 
# Relies on presence of mds02.py, generated by:
#   ctypesgen.py -o mds02.py faketime_t.h mds02.h
#with faketime_t.h containing, e.g:
#    typedef int time_t;
# to force a particular type for time_t (it varies with system)

import sysv_ipc
from mds02 import *
from ctypes import *

shared_memory_id=18087947 # integer 

TEMP_CONST=38.967854 # from http://www.csgnetwork.com/machonecalc.html

imem = sysv_ipc.attach(shared_memory_id)
misc = Misc()

sizeofplane=sizeof(Plane) 
#sizeofplane= #for some reason

#Structure of shared memory is P_MAX Plane instances followed my a Misc

#unpack Misc
misc_address = imem.address + (P_MAX + 1)*sizeofplane
memmove(addressof(misc), misc_address, sizeof(Misc))

P_MAX_C= misc.P_MAX_C
planes = []

#unpack plane (0 is dummy empty record?)
for i in range (0, P_MAX_C):
   planes.append(Plane())
   pi = addressof(planes[i])
   memmove(pi, imem.address + i *sizeofplane, sizeofplane)

#memstring=imem.read()
#print memstring.find('MUSIC')
#print memstring.find('EZY89JU')

print 'Ident, Latitude, Longitude, Altitude / ft, T / °C'

for i in range (0, P_MAX_C):
   if(planes[i].id <> 0):
      TK = (planes[i].bds.tas_50/(planes[i].bds.mach_60*TEMP_CONST))**2
      TC = TK - 273.15
  
      print '%9s, %6.4f, %6.4f, %6.0d, %4.2f' % (planes[i].acident, planes[i].lat, planes[i].lon, planes[i].alt, TC)
